---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-ott
  template:
    metadata:
      labels:
        app: my-ott
    spec:
      containers:
      - name: cont-1
        image: avinash1836/anime:luffy
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ott
spec:
  type: NodePort
  selector:
    app: my-ott
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30001
